iio-buffer-utils: Fix cast-align warnings on ARM
iio-buffer-utils.c: In function 'process_scan_1':
iio-buffer-utils.c:495:20: error: cast increases required alignment of target type [-Werror=cast-align]
     guint32 val = *(guint32 *) (data + buffer_data->channels[k]->location);
                    ^
iio-buffer-utils.c:501:19: error: cast increases required alignment of target type [-Werror=cast-align]
     gint32 val = *(gint32 *) (data + buffer_data->channels[k]->location);
                   ^

Looks like there's no need to cast.

Closes: #113